[package]
name = "mcumgr-client-wrapper"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mcumgr_client"
crate-type = ["cdylib"]

[dependencies]
mcumgr-client = { path = "mcumgr-client" }

[dependencies.pyo3]
version = "0.28.2"
features = ["abi3-py310"]