[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "mcumgr-client-wrapper"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
description = "Python bindings for the rust library mcumgr-client"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
  { name="Adrien Bruant" },
  { name="Baptiste Cluzel" },
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/comap-smart-home/mcumgr-client-wrapper"
